### ISSUE TITLE
Duplicate Order ID

### ISSUE THREAD

**Issue by fvdbijl** [ICEPAY/WooCommerce#2]
Hi, 

I had contact with Icepay. They said I could create a ticket over here and that you could solve it. I get the error in WooCommerce that there is already a duplicate order ID. With that error the customer can't complete the payment and order. As you probably understand this is a problem for us as shop and the customer. 

I'm looking forward to the solution. 

Kind regards, 

Frits

**Comment by tsygankov** [comment]
Hi Frits,

That's a known problem that some users experience when setting up integration with ICEPAY. ICEPAY Payment Gateway does not allow using same order ID more than once. Order ID must be unique within the scope of each website (Merchant ID). For example, if your website sent a payment request to ICEPAY Payment Gateway and specified order number was 0000123, you won't be able to send another payment request with the same order number. Usually web-shops use sequences for order numbering and automatically increment order number each time you create a new order, so normally this is not an issue. However if you've changed order numbering or used same Merchant ID (website) in another environment (for example making test transactions in development or test env), you probably will receive duplicate order ID message. 
To solve the problem you can adjust order numbering and ensure that your web-shop is sending orders with unique order ID. Another option is to get a new Merchant ID for your website, however the problem will appear again if web-shop is generating non-unique order IDs.

Please let me know if you have any further questions.

Best regards,
Stan

**Comment by fvdbijl** [comment]
Hi Stan, 

Thank you for the reply. Can you help me adjust order numbering? I have the idea that the problem occurs when customers dont finish their order in once. For example they return from the payment and try to pay again, then it goes wrong. For me that seems like the page wont 'refresh' the order ID. This seems different to me than the testing, also because I have only tested it little and this error occurs quite often. 

Isnt it possible to change this in code? Jeroen from Icepay on the phone told me that there is also an other unique ID that should be sufficient. 

When typing this I think it might be the problem that the same Merchant ID was working on our old website. Might that be the struggle?

Looking forward hearing from you.

Frits

**Comment by tsygankov** [comment]
Then it looks like a bug in the payment module. I will try to reproduce the issue in our test environment. Can you please specify WordPress, WooCommerce and ICEPAY Payment Module versions that you are using?

Stan

**Comment by fvdbijl** [comment]
You can also try it on our site: http://www.hetkoffiecultuurcentrum.nl/. Try to move back and forward a few times in the payment and you will get the error

As far as I know everything is updated. 
Woocommerce 2.6.7
Icepay 2.3.6
Wordpress 4.6.1

**Comment by tsygankov** [comment]
Ok, I'm on it

**Comment by fvdbijl** [comment]
Great :)

**Comment by tsygankov** [comment]
// Process payment
				if ( WC()->cart->needs_payment() ) {

					// Store Order ID in session so it can be re-used after payment failure
					WC()->session->order_awaiting_payment = $order_id;

					// Process Payment
					$result = $available_gateways[ $this->posted['payment_method'] ]->process_payment( $order_id );

WooCommerce is reusing Order ID if there was if previous payment fails, however, I see that ICEPAY Payment Module for WooCommerce v2.3.6 is using a generated Order ID instead of WooCommerce Order ID, so there shouldn't be any problems.

                // Add transaction to ICEPAY table
                $wpdb->insert($this->getTableWithPrefix('woocommerce_icepay_transactions'), array('order_id' => $order_id, 'status' => Icepay_StatusCode::OPEN, 'transaction_id' => NULL));
                $lastid = $wpdb->insert_id;

                $paymentObj = new Icepay_PaymentObject();
                $paymentObj->setOrderID($lastid)

I have several test-cases, I need some time to check. 

Can you please specify PHP and MySQL versions also?

**Comment by fvdbijl** [comment]
PHP version 5.5, MySQL 5.5.31

**Comment by fvdbijl** [comment]
I think the problem is indeed in the Icepay generated Order ID instead of the WooCommerce Order ID. I also tried to use sequential WooCommerce Order ID's but this doesnt change anything

**Comment by tsygankov** [comment]
Yes, I'm quite sure that problem is in the module. We will continue working on this issue today. I will get back to you later.

**Comment by tsygankov** [comment]
I could not reproduce the issue on our test environment. Could you please contact us by email icepay@balticsolutions.lv ? We need more information about your website.

**Comment by fvdbijl** [comment]
Hi Stan, I have send you an email.

**Comment by tsygankov** [comment]
I replied on your email ~1 hour ago, please check your Spam folder just in case the email got delivered there instead of your inbox.

**Comment by tsygankov** [comment]
I’m closing old issues. Please reopen if this is still a problem for you or if you can provide more details.
