### ISSUE TITLE
WooCommerce incompatibility

### ISSUE THREAD

**Issue by ronnybye** [ICEPAY/WooCommerce#3]
my technical reports that its module is failing on line 70, specifically in this instruction (file: icepay.php)

$loaded_gateways = apply_filters('woocommerce_payment_gateways', array());

Please tell me what can i do?
at the moment the technician has canceled that line and apparently the module works but not sure if will this affects the management process ICEPAY.

Regards
Ronny Bye

**Comment by tsygankov** [comment]
Hi Ronny,

Can you please specify the error message that you receive when the problem occurs?

Please also specify WordPress, WooCommerce and ICEPAY Payment Module version.

Kind regards,
Stanislav Tsygankov

**Comment by ronnybye** [comment]
Hi, 
Thanks  for your answer..
I have a questions: My technical is Spanish and doesn't speak english can you give the support in spanish leguage?

Anyway I attached the file where show the error in the plugin and the info requested.

WordPres 4.5.3
WooCommerec 2.6.4
ICEPAY Payment Module for WooCommerce Version 2.3.6

[error-plugin.pdf](https://github.com/ICEPAYdev/WooCommerce/files/588029/error-plugin.pdf)

Regards
Ronny Bye

**Comment by tsygankov** [comment]
Unfortunately we don't have employees that speak Spanish, but I think you can write comments in Spanish anyway. We will try to use Google Translate :)

We will try to reproduce the problem on our test server using the same software version as you use. Can you please also specify the PHP version?

error-plugin.pdf
In the attached file we can see the PHP call stack, but error message is not shown. Can you please attach the error message also? If it contains sensitive information (like domain name, IP address and etc) please send it to modules@icepay.com

Error message example:
![error_message_example](https://cloud.githubusercontent.com/assets/15112699/20355557/58fbb348-ac2a-11e6-86b7-e4b84d766c07.PNG)

**Comment by ronnybye** [comment]
Hello,
Here is the info that my technician gave me:
PHP Version: 5.6.25
dominio: respiramax.com
IP: 192.186.230.232

**Comment by tsygankov** [comment]
I edited your comment. Please do not publish any sensitive information here, it can be used to compromise your website.

**Comment by ronnybye** [comment]
Thank you !

**Comment by tsygankov** [comment]
I’m closing old issues. Please reopen if this is still a problem for you or if you can provide more details.
